In [1]:
#import numpy library
import numpy as np

In [23]:
#create two matrices M1 (2x3) and M2 (3x2) and print them

##Write your code below this##
M1=np.array([[1,2,3],[3,4,5]])
print(M1)
print("Shape of M1",M1.shape)
M2=np.array([[5,6],[7,8],[9,0]])
print(M2)
print("Shape of M2",M2.shape)
##Write your code above this##

[[1 2 3]
 [3 4 5]]
Shape of M1 (2, 3)
[[5 6]
 [7 8]
 [9 0]]
Shape of M2 (3, 2)


In [24]:
#Multiply (Matrix Multiplication) M1 and M2 and store the results in M3, print M3

##Write your code below this##
M3=np.matmul(M1,M2)
print(M3)
##Write your code above this##

[[46 22]
 [88 50]]


In [52]:
#Create a column vector of the size 6x1 and convert it to a matrix of the size 3x2

##Write your code below this##
v1=np.random.rand(6,1)
v1=v1.reshape(3,2)
v1

##Write your code above this##

array([[0.78241607, 0.68186238],
       [0.34231922, 0.46272443],
       [0.5065235 , 0.19980316]])

In [48]:
#create a random matrix of size 2x3 and multiply it with an identity matrix, print the results you get?

##Write your code below this##
r=np.random.rand(2,3)
s=np.identity(3)
t=np.matmul(r,s)
print(t)
##Write your code above this##

[[0.17248025 0.10918574 0.41512743]
 [0.9525259  0.01625779 0.5707278 ]]
