In [1]:
#import numpy library
import numpy as np

In [2]:
#create a row vector v1 as a numpy array
v1 = np.array([1, 2, 3, 4])

#print the v1 vector
print(v1)

#print shape of the array, observe last argument after ,
print(v1.shape)

[1 2 3 4]
(4,)


In [3]:
#create a row vector v2 as a numpy array
v2 = np.array([1.0, 2.0, 3.0, 4.0])

#print the v2 vector
print(v2)

#print shape of the array, observe last argument after ,
print(v2.shape)

[1. 2. 3. 4.]
(4,)


In [4]:
#create a column vector v3 as a numpy array
v3 = np.array([[1],[2],[3],[4]])

#print the v3 vector
print(v3)

#print shape of the array, observe last argument after ,
print(v3.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [5]:
#create a column vector v4 of strings as a numpy array
v4 = np.array([['India'],['USA'],['UK'],['Russia']])

#print the v4 vector
print(v4)

#print shape of the array, observe last argument after ,
print(v4.shape)

[['India']
 ['USA']
 ['UK']
 ['Russia']]
(4, 1)


In [6]:
#add v1, v2 and save it to v5
v5 = v1+v2

#print the v5 vector
print(v5)

#print shape of the array, observe last argument after ,
print(v5.shape)

[2. 4. 6. 8.]
(4,)


In [7]:
#multiply v1, v2 and save it to v6
v6 = v1*v2

#print the v6 vector
print(v6)

#print shape of the array, observe last argument after ,
print(v6.shape)

[ 1.  4.  9. 16.]
(4,)


In [8]:
#create 2x2 matrix A
A = np.array([[1,2],[3,4]])

#print the matrix
print(A)

print(A.shape)

[[1 2]
 [3 4]]
(2, 2)


In [9]:
#create another 2x2 matrix B
B = np.array([[5,6],[7,8]])

#print the matrix
print(B)

print(B.shape)

[[5 6]
 [7 8]]
(2, 2)


In [10]:
#C = A+B
C = A+B

#print the matrix
print(C)

print(C.shape)

[[ 6  8]
 [10 12]]
(2, 2)


In [11]:
#D = AxB
D = A*B

#print the matrix and check the result
print(D)

print(D.shape)

[[ 5 12]
 [21 32]]
(2, 2)


In [12]:
#E = A*B (Matrix Multiplication)
E = np.matmul(A,B)

#print the matrix and check the result - This result is different than previous cell, why?
print(E)

print(E.shape)

[[19 22]
 [43 50]]
(2, 2)


In [13]:
#Create matrix of zeros of the size 3x4
Z = np.zeros((3,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#Create identity matrix
I = np.identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:

#Create a random matrix
R = np.random.rand(4,4)
print(R)

[[0.06442327 0.33759427 0.00492211 0.2078379 ]
 [0.34841314 0.29280966 0.49773439 0.61034942]
 [0.47720909 0.0273487  0.80492844 0.14560915]
 [0.01662968 0.76768731 0.95524208 0.13493224]]


In [18]:
#Transpose of a matrix
T1 = np.array([[1,2],[3,4],[5,6]])
print("T1:")
print(T1)
T1.transpose()
#T2 = np.matrix.transpose(T1)
#print("\n\nTranspose of T1:")
#print(T2)

T1:
[[1 2]
 [3 4]
 [5 6]]


array([[1, 3, 5],
       [2, 4, 6]])

In [28]:
#Reshape
X1 = np.array([[1,2],[3,4],[5,6]])
print("X1:")
print(X1)

X2 = X1.reshape(6)
print("\n\nX2:")
print(X2)

X1:
[[1 2]
 [3 4]
 [5 6]]


X2:
[1 2 3 4 5 6]
