In [21]:
#import
import numpy as np
import pandas as pd  

In [22]:
#load data from csv file
dataset = pd.read_csv('housing.csv')
#dataset = pd.read_csv('housing.csv',delimiter=';')
#dataset = pd.read_csv('housing.csv',delimiter=';',skiprows=1)

In [23]:
#display initial rows
#dataset.head()
dataset.head(10)  #display first 10 rows

bedrooms  bathrooms  sqft_living  floors    price
0         3       1.00         1180     1.0   221900
1         3       2.25         2570     2.0   538000
2         2       1.00          770     1.0   180000
3         4       3.00         1960     1.0   604000
4         3       2.00         1680     1.0   510000
5         4       4.50         5420     1.0  1225000
6         3       2.25         1715     2.0   257500
7         3       1.50         1060     1.0   291850
8         3       1.00         1780     1.0   229500
9         3       2.50         1890     2.0   323000

In [24]:
#display last rows
#dataset.tail()
dataset.tail(10)  #display last 10 rows

bedrooms  bathrooms  sqft_living  floors    price
21603         3       2.50         2270     2.0   507250
21604         3       2.00         1490     3.0   429000
21605         4       2.50         2520     2.0   610685
21606         4       3.50         3510     2.0  1007500
21607         3       2.50         1310     2.0   475000
21608         3       2.50         1530     3.0   360000
21609         4       2.50         2310     2.0   400000
21610         2       0.75         1020     2.0   402101
21611         3       2.50         1600     2.0   400000
21612         2       0.75         1020     2.0   325000

In [25]:
#display complete dataset
dataset

bedrooms  bathrooms  sqft_living  floors   price
0             3       1.00         1180     1.0  221900
1             3       2.25         2570     2.0  538000
2             2       1.00          770     1.0  180000
3             4       3.00         1960     1.0  604000
4             3       2.00         1680     1.0  510000
...         ...        ...          ...     ...     ...
21608         3       2.50         1530     3.0  360000
21609         4       2.50         2310     2.0  400000
21610         2       0.75         1020     2.0  402101
21611         3       2.50         1600     2.0  400000
21612         2       0.75         1020     2.0  325000

[21613 rows x 5 columns]

In [34]:
X = dataset.iloc[:,:-1]
print(X)

       bedrooms  bathrooms  sqft_living  floors
0             3       1.00         1180     1.0
1             3       2.25         2570     2.0
2             2       1.00          770     1.0
3             4       3.00         1960     1.0
4             3       2.00         1680     1.0
...         ...        ...          ...     ...
21608         3       2.50         1530     3.0
21609         4       2.50         2310     2.0
21610         2       0.75         1020     2.0
21611         3       2.50         1600     2.0
21612         2       0.75         1020     2.0

[21613 rows x 4 columns]


In [35]:
y = dataset.iloc[:,-1:]
print(y)
print(type(y))

        price
0      221900
1      538000
2      180000
3      604000
4      510000
...       ...
21608  360000
21609  400000
21610  402101
21611  400000
21612  325000

[21613 rows x 1 columns]
<class 'pandas.core.frame.DataFrame'>


In [36]:
print(X['bedrooms'])

0        3
1        3
2        2
3        4
4        3
        ..
21608    3
21609    4
21610    2
21611    3
21612    2
Name: bedrooms, Length: 21613, dtype: int64


In [37]:
y_np = np.array(y)
print(y_np)
print(y_np.shape)

[[221900]
 [538000]
 [180000]
 ...
 [402101]
 [400000]
 [325000]]
(21613, 1)


In [38]:
X_np = np.matrix(X)
print(X_np)
print(X_np.shape)

[[3.00e+00 1.00e+00 1.18e+03 1.00e+00]
 [3.00e+00 2.25e+00 2.57e+03 2.00e+00]
 [2.00e+00 1.00e+00 7.70e+02 1.00e+00]
 ...
 [2.00e+00 7.50e-01 1.02e+03 2.00e+00]
 [3.00e+00 2.50e+00 1.60e+03 2.00e+00]
 [2.00e+00 7.50e-01 1.02e+03 2.00e+00]]
(21613, 4)


Practice

In [57]:
#Sort the values of y or y_np

#Writer your code below this line#
s=sorted(y_np)
s
#Write your code above this line#

[array([75000], dtype=int64),
 array([78000], dtype=int64),
 array([80000], dtype=int64),
 array([81000], dtype=int64),
 array([82000], dtype=int64),
 array([82500], dtype=int64),
 array([83000], dtype=int64),
 array([84000], dtype=int64),
 array([85000], dtype=int64),
 array([85000], dtype=int64),
 array([86500], dtype=int64),
 array([89000], dtype=int64),
 array([89950], dtype=int64),
 array([90000], dtype=int64),
 array([90000], dtype=int64),
 array([90000], dtype=int64),
 array([90000], dtype=int64),
 array([90000], dtype=int64),
 array([92000], dtype=int64),
 array([95000], dtype=int64),
 array([95000], dtype=int64),
 array([95000], dtype=int64),
 array([95000], dtype=int64),
 array([96500], dtype=int64),
 array([99000], dtype=int64),
 array([100000], dtype=int64),
 array([100000], dtype=int64),
 array([100000], dtype=int64),
 array([100000], dtype=int64),
 array([100000], dtype=int64),
 array([100000], dtype=int64),
 array([102500], dtype=int64),
 array([104950], dtype=int64),
 a

In [43]:
#Print total_bedrooms column from X

#Writer your code below this line#
b=X['bedrooms'].sum()
b
#Write your code above this line#

72854

In [68]:
#Print number of records having 4 bedrooms

#Writer your code below this line#
rooms=[4]
dataset[dataset.bedrooms.isin(rooms)]
#dataset.nlargest(4,['bedrooms'])
#dataset['bedrooms'].max()
#Write your code above this line#

bedrooms  bathrooms  sqft_living  floors    price
3             4       3.00         1960     1.0   604000
5             4       4.50         5420     1.0  1225000
15            4       3.00         2950     2.0   650000
17            4       1.00         1600     1.5   485000
20            4       1.75         1620     1.0   385000
...         ...        ...          ...     ...      ...
21598         4       2.50         3118     2.0   541800
21599         4       3.00         3990     2.0   810000
21605         4       2.50         2520     2.0   610685
21606         4       3.50         3510     2.0  1007500
21609         4       2.50         2310     2.0   400000

[6882 rows x 5 columns]